name: release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  goreleaser:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: vars
        run: |
          goVersion=$(grep '^FROM go' .github/go/Dockerfile | cut -d ' ' -f 2 | cut -d ':' -f 2)
          echo "go_version=${goVersion}" >> $GITHUB_OUTPUT
          echo "Using Go version ${goVersion}"

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ steps.vars.outputs.go_version }}

      - name: Release dry run
        run: make release-dry-run

      - name: Setup release environment
        run: echo 'GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}' > .release-env

      - name: Release publish
        run: make release
